version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: assettree-backend
    restart: always
    environment:
      - PORT=8000
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2048M
    ports:
      - "8001:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: assettree-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
